services:
  app:
    stdin_open: true
    tty: true
    image: container-hivwc7q
    build:
      context: ./src
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./src/web
        target: /var/www/html
    environment:
      ALLOWED_HOSTS: "127.0.0.1,localhost"

